#!/bin/bash

# This script uses mingw and the GNU tool chain for cross-compiling under
# linux. You can change the variables to not cross-compile for running
# with MSYS on windows. Whichever you choose, you need to provide the
# following as described and review the commands.

# static libs: libiconv, libintl, winpthread, libenet
# shared libs: sdl2, openal, curl

# libenet is not currently provided as a package in mingw distributions.
# The thing to check is that if pkgconfig is used, the one generated by
# libenet's make install does not have the proper libs for windows.
# Check that -lws2_32 and -lwinmm are libs in libenet.pc, as pkgconfig files
# are preferred by CMake's find_package.

# Finally, you will need TeXLive to build the manual.

HOST=i686-w64-mingw32.shared
HOST_OPT="-DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=${HOST}-gcc -DCMAKE_CXX_COMPILER=${HOST}-g++"
STRIP=${HOST}-strip

mkdir -p build
cd build
cmake .. $HOST_OPT -DCMAKE_BUILD_TYPE=Release
cmake --build . -j6
cmake --install . --prefix ../dest
cd ..
$STRIP dest/bin/10kingdoms.exe

cd doc
latexmk
cd ..
cp doc/main.pdf dest/10kingdoms-manual.pdf

# Still need to add music and dlls
# then run NSIS on install.nsi
